# Generated by Django 3.0.7 on 2020-06-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date', '-updated_date']},
        ),
    ]
