# Generated by Django 3.0.7 on 2020-07-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Recipes', max_length=20),
        ),
    ]
