# Generated by Django 3.0.7 on 2021-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20210606_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.ImageField(default='x', upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image3',
            field=models.ImageField(default='x', upload_to='blog_image'),
            preserve_default=False,
        ),
    ]
