# Generated by Django 3.0.7 on 2021-06-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20210606_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image2',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image3',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
    ]
