# Generated by Django 3.1.9 on 2021-06-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_newsletteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='name',
            field=models.CharField(default='john dick', max_length=200),
            preserve_default=False,
        ),
    ]
