# Generated by Django 3.0.7 on 2020-07-13 19:55

import blogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='recipes', max_length=20, verbose_name=blogapp.models.Category),
        ),
    ]
