# Generated by Django 3.1.9 on 2021-06-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_newsletteruser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletteruser',
            name='name',
        ),
    ]
