# Generated by Django 3.1.9 on 2021-06-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_remove_newsletteruser_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterUser',
        ),
    ]
