# Generated by Django 3.1.9 on 2021-06-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_newsletteruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterUser',
        ),
    ]
