# Generated by Django 3.1.9 on 2021-06-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
