# Generated by Django 3.1.9 on 2021-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_delete_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='media')),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=30)),
            ],
        ),
    ]
