# Generated by Django 3.0.7 on 2020-07-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='Subscribe',
        ),
    ]
