# Generated by Django 3.0.7 on 2020-07-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200703_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
