# Generated by Django 3.0.7 on 2020-07-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_subscribe_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='featured',
            new_name='terms',
        ),
    ]
