# Generated by Django 3.0.7 on 2020-07-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20200703_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='terms',
        ),
    ]
